<a href="https://colab.research.google.com/github/waseem007230/assignment01/blob/master/Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
a = {1, 2, 3}
b = {0, 3, 4, 5}
print(a & b)


{3}


In [ ]:
'''you are analyzing sales data from a ticket office.
The ticket for an adult is $20, while the ticket for a child under 18 is $5.
The data you are given is in a dictionary format, where the keys are the sold ticket numbers, and the values are the customer ages.
For example, "123-08": 24 means that the ticket was bought a 24 year old.
Your goal is to calculate how much more money the office would make if it would change the ticket discount age to the given input.
So, your program needs to take an integer as input and output the percentage of revenue growth, if the discount was given to people under that age.

For example, if the office made $15000 with the original discount age, and would make $18000 with 14 as the discount age, then the growth would be ((18000-15000)/15000)*100 = 20%

So, for the input 14, your program should output 20. The output should be an integer (use int() to convert the result).'''
data = {
    "100-90": 25, "42-01": 48, "55-09": 12, "128-64": 71, "002-22": 18, "321-54": 19, "097-32": 33, "065-135": 64, "99-043": 80, "111-99": 11, "123-019": 5, "109-890": 72, "132-123": 27, "32-908": 27, "008-09": 25, "055-967": 35, "897-99": 44, "890-98": 56, "344-32": 65, "43-955": 59, "001-233": 9, "089-111": 15, "090-090": 17, "56-777": 23, "44-909": 27, "13-111": 21, "87-432": 15, "87-433": 14, "87-434": 23, "87-435": 11, "87-436": 12, "87-437": 16, "94-121": 15, "94-122": 35, "80-089": 10, "87-456": 8, "87-430": 40
}
age = int(input())

total_first=0
total_second=0

for value in data.values():
    if value<18:    
        total_first+=5
    if value>=18:
        total_first+=20
        
for value in data.values():
    if value<age:
        total_second+=5
    if value>=age:
        total_second+=20
        
        
x=int(((total_second-total_first)/total_first)*100) 
print(x)


##**numpy Library**
* numpy : stands for **Numerical Python**
* Like list in Python, array is a datastructure for numpy


* Python List is a collection of heterogenous datatypes items. It takes huge amount of time and memory for numerical computations of large data.
* Numpy array is a collection of homogenous datatypes items. It takes  very little amount of memory and time in comparision with list in terms of numerical computation of large data.

In [13]:
import numpy as np

In [ ]:
# a = []
np.array([1,2,3])

In [ ]:
a  = np.array([1,2,3])
type(a)

In [ ]:
a  = np.array([1,2.3,'3',[1,2],(3,4),{1:2}])
print(a,type(a))

In [ ]:
a = [1,2,3,4,5]
a = np.array(a)
a

In [ ]:
# np.arange(5)
# np.arange(5,10)
# np.arange(1,10,2)

The number of dimensions and items in an array is defined by its shape.
The dimensions are also called as axes.
ndarray : n-Dimensional array
0D - Scalar
1D Array - Vector
2D Array - Matrix
3D or more (Multi Dimension) - Tensor

In [7]:
a = [1,2]
b = [3,4]
c = np.array([a,b])
c
# type(c)

In [11]:
c.size

numpy.ndarray

In [10]:
a = [1,2,3]
b = [3,4,5]
c = [5,6,7]
d = np.array([a,b,c])
d
# type(c)

array({1, 2, 3}, dtype=object)

In [ ]:
# sie gives total number of elements in the arrays
d.size

In [ ]:
d.shape

In [ ]:
d.ndim

In [ ]:
print(d)
# d.reshape(1,9)
# d.reshape(9,1)

In [ ]:
# Alternative reshaping
d.shape = (9,1)

In [ ]:
Zero = np.array(10) # Scalar
one = np.array([1,2,3,4,5]) # Vector
two = np.array([[1,2],[3,4]]) # or np.array([arr,arr]) # Matrix
three = np.array([[[1,2],[3,4],[5,6]]]) # 3D Tensor
four = np.array([[[[1,2],[3,4],[5,6]]]]) # 4D Tensor

In [ ]:
# Zero.ndim
# one.ndim
four.ndim

In [ ]:
# zero = np.array(1)
# zero.ndim

# one = np.ones(1)
# one = np.ones(2)
one = np.ones(3)
one

In [ ]:
# np.array([np.ones(3),np.ones(3),np.ones(3)])
np.ones((3,3))

In [ ]:
# np.zeros(1)
np.zeros((2,5))

In [ ]:
# np.zeros((0,2,5))
# np.zeros((1,2,5))
# np.zeros((2,2,5))
np.zeros((3,2,5))
# np.zeros((4,2,5))


In [ ]:
# np.full(number of items, value)
np.full(1,2)
np.full(2,2)
np.full(3,2)

SLICING

In [15]:
A = np.array([1,2,3,4,5])

In [20]:
A[:5:2]

array([1, 3, 5])

In [32]:
a = [1,2,3]
b = [3,4,5]
c = [5,6,7]
d = np.array([a,b,c])
# array_name[row_start_val:row_end_val, col_start_val:col_end_val]
# print(d)
d[0:2,1:]

array([[2, 3],
       [4, 5]])

In [33]:
d[1:3,0:2]

array([[3, 4],
       [5, 6]])

In [42]:
a = [1,2,3]
b = [3,4,5]
c = [5,6,7]
d[1:3,1:2]

array([[4],
       [6]])

In [44]:
c= np.array([[1, 2, 3, 4, 5],
       [6,7,8,9,10],
       [11, 12, 13, 14, 15]])
c


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [67]:
# c[1:3,1:4]
# c[2:,2:4]
# c[0:2,0::3]
# c[1:3,1::3]
# c[0:2,1:4:2]
# c[1:3,2::2]
c[2:,0::2]


array([[11, 13, 15]])

In [57]:
c[2:,2:4]
c[0:2,0::3]
c[1:3,1::3]
c[0:3,1::2]

array([[ 2,  4],
       [ 7,  9],
       [12, 14]])

In [74]:
# np.linspace(start,end,equally_spacing_value)
np.linspace(1,30,5)

array([ 1.  ,  8.25, 15.5 , 22.75, 30.  ])

In [ ]:
a = np.arange(10)
a  = np.append(a,10)
a

In [75]:
a = np.arange(10)
a  = np.append(a,[10,11,12])
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [77]:
a = np.arange(10)
a  = np.delete(a,6)
a

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

In [78]:
a = np.arange(10)
a  = np.delete(a,[1,3,5,7])
a

array([0, 2, 4, 6, 8, 9])

In [76]:
a = np.array([7,4,9,6,8,2])
np.sort(a)

array([2, 4, 6, 7, 8, 9])

In [79]:
a = np.array([7,4,9,6,8,2])
np.sqrt(a)

array([2.64575131, 2.        , 3.        , 2.44948974, 2.82842712,
       1.41421356])

In [80]:
a = np.array([7,4,9,6,8,2])
np.exp(a)

array([1.09663316e+03, 5.45981500e+01, 8.10308393e+03, 4.03428793e+02,
       2.98095799e+03, 7.38905610e+00])

In [84]:
# np.random.rand(5)
np.random.randint(1,10,2)

array([6, 3])

In [85]:
np.random.randn(2)

array([-0.09242904,  1.11156212])

Airthmetic with arrays

In [86]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [88]:
a=np.array([1,2,3])
b=np.array([6,5,4])
a-b

array([-5, -3, -1])

In [89]:
a=np.array([1,2,3])
b=np.array([6,5,4])
a*b

array([ 6, 10, 12])

In [93]:
b=np.array([1,2,3])
a=np.array([6,5,4])
a//b

array([6, 2, 1])

In [95]:
# it will add,sub,mul,div 5 to each elements in the array it is a scalar (add mul sub div) 
a=np.array([6,5,4])
a*5

array([30, 25, 20])

In [ ]:
a = np.array([1,2,3])
# a+4 #scalar addition
# a-4 #scalar subtraction
a*2 # scalar multiplication
a/2 # scalar division

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

b=np.array([7,8])
a+b

In [119]:
a=np.array([[1,2,3],
            [4,5,6]])
b=np.array([0,2,6])
a<b

array([[False, False,  True],
       [False, False, False]])

Statistical methods

In [122]:
a = np.arange(5)
print(a)
np.mean(a) 

[0 1 2 3 4]


2.0

In [ ]:
a = np.arange(5)
print(a)
np.median(a) 

In [121]:
a = np.arange(5)
print(a)
np.std(a) 

[0 1 2 3 4]


1.4142135623730951